// Mocks generated by Mockito 5.4.6 from annotations
// in later_mobile/test/features/home/presentation/controllers/content_filter_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:later_mobile/features/lists/application/services/list_service.dart'
    as _i10;
import 'package:later_mobile/features/lists/domain/models/list_item_model.dart'
    as _i6;
import 'package:later_mobile/features/lists/domain/models/list_model.dart'
    as _i5;
import 'package:later_mobile/features/notes/application/services/note_service.dart'
    as _i7;
import 'package:later_mobile/features/notes/domain/models/note.dart' as _i2;
import 'package:later_mobile/features/todo_lists/application/services/todo_list_service.dart'
    as _i9;
import 'package:later_mobile/features/todo_lists/domain/models/todo_item.dart'
    as _i4;
import 'package:later_mobile/features/todo_lists/domain/models/todo_list.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNote_0 extends _i1.SmartFake implements _i2.Note {
  _FakeNote_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTodoList_1 extends _i1.SmartFake implements _i3.TodoList {
  _FakeTodoList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTodoItem_2 extends _i1.SmartFake implements _i4.TodoItem {
  _FakeTodoItem_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListModel_3 extends _i1.SmartFake implements _i5.ListModel {
  _FakeListModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListItem_4 extends _i1.SmartFake implements _i6.ListItem {
  _FakeListItem_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NoteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteService extends _i1.Mock implements _i7.NoteService {
  MockNoteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i2.Note>> getNotesForSpace(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesForSpace, [spaceId]),
            returnValue: _i8.Future<List<_i2.Note>>.value(<_i2.Note>[]),
          )
          as _i8.Future<List<_i2.Note>>);

  @override
  _i8.Future<_i2.Note> createNote(_i2.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#createNote, [note]),
            returnValue: _i8.Future<_i2.Note>.value(
              _FakeNote_0(this, Invocation.method(#createNote, [note])),
            ),
          )
          as _i8.Future<_i2.Note>);

  @override
  _i8.Future<_i2.Note> updateNote(_i2.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i8.Future<_i2.Note>.value(
              _FakeNote_0(this, Invocation.method(#updateNote, [note])),
            ),
          )
          as _i8.Future<_i2.Note>);

  @override
  _i8.Future<void> deleteNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.Note> toggleFavorite(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [id]),
            returnValue: _i8.Future<_i2.Note>.value(
              _FakeNote_0(this, Invocation.method(#toggleFavorite, [id])),
            ),
          )
          as _i8.Future<_i2.Note>);

  @override
  _i8.Future<_i2.Note> archiveNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#archiveNote, [id]),
            returnValue: _i8.Future<_i2.Note>.value(
              _FakeNote_0(this, Invocation.method(#archiveNote, [id])),
            ),
          )
          as _i8.Future<_i2.Note>);

  @override
  _i8.Future<_i2.Note> unarchiveNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#unarchiveNote, [id]),
            returnValue: _i8.Future<_i2.Note>.value(
              _FakeNote_0(this, Invocation.method(#unarchiveNote, [id])),
            ),
          )
          as _i8.Future<_i2.Note>);
}

/// A class which mocks [TodoListService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoListService extends _i1.Mock implements _i9.TodoListService {
  MockTodoListService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i3.TodoList>> getTodoListsForSpace(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodoListsForSpace, [spaceId]),
            returnValue: _i8.Future<List<_i3.TodoList>>.value(<_i3.TodoList>[]),
          )
          as _i8.Future<List<_i3.TodoList>>);

  @override
  _i8.Future<_i3.TodoList> createTodoList(_i3.TodoList? todoList) =>
      (super.noSuchMethod(
            Invocation.method(#createTodoList, [todoList]),
            returnValue: _i8.Future<_i3.TodoList>.value(
              _FakeTodoList_1(
                this,
                Invocation.method(#createTodoList, [todoList]),
              ),
            ),
          )
          as _i8.Future<_i3.TodoList>);

  @override
  _i8.Future<_i3.TodoList> updateTodoList(_i3.TodoList? todoList) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodoList, [todoList]),
            returnValue: _i8.Future<_i3.TodoList>.value(
              _FakeTodoList_1(
                this,
                Invocation.method(#updateTodoList, [todoList]),
              ),
            ),
          )
          as _i8.Future<_i3.TodoList>);

  @override
  _i8.Future<void> deleteTodoList(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodoList, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> reorderTodoLists(
    String? spaceId,
    List<String>? orderedIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderTodoLists, [spaceId, orderedIds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.TodoItem>> getTodoItemsForList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodoItemsForList, [listId]),
            returnValue: _i8.Future<List<_i4.TodoItem>>.value(<_i4.TodoItem>[]),
          )
          as _i8.Future<List<_i4.TodoItem>>);

  @override
  _i8.Future<_i4.TodoItem> createTodoItem(_i4.TodoItem? todoItem) =>
      (super.noSuchMethod(
            Invocation.method(#createTodoItem, [todoItem]),
            returnValue: _i8.Future<_i4.TodoItem>.value(
              _FakeTodoItem_2(
                this,
                Invocation.method(#createTodoItem, [todoItem]),
              ),
            ),
          )
          as _i8.Future<_i4.TodoItem>);

  @override
  _i8.Future<_i4.TodoItem> updateTodoItem(_i4.TodoItem? todoItem) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodoItem, [todoItem]),
            returnValue: _i8.Future<_i4.TodoItem>.value(
              _FakeTodoItem_2(
                this,
                Invocation.method(#updateTodoItem, [todoItem]),
              ),
            ),
          )
          as _i8.Future<_i4.TodoItem>);

  @override
  _i8.Future<void> deleteTodoItem(String? id, String? todoListId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodoItem, [id, todoListId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i4.TodoItem> toggleTodoItem(String? id, String? todoListId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTodoItem, [id, todoListId]),
            returnValue: _i8.Future<_i4.TodoItem>.value(
              _FakeTodoItem_2(
                this,
                Invocation.method(#toggleTodoItem, [id, todoListId]),
              ),
            ),
          )
          as _i8.Future<_i4.TodoItem>);

  @override
  _i8.Future<void> reorderTodoItems(String? listId, List<String>? orderedIds) =>
      (super.noSuchMethod(
            Invocation.method(#reorderTodoItems, [listId, orderedIds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [ListService].
///
/// See the documentation for Mockito's code generation for more information.
class MockListService extends _i1.Mock implements _i10.ListService {
  MockListService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i5.ListModel>> getListsForSpace(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getListsForSpace, [spaceId]),
            returnValue: _i8.Future<List<_i5.ListModel>>.value(
              <_i5.ListModel>[],
            ),
          )
          as _i8.Future<List<_i5.ListModel>>);

  @override
  _i8.Future<_i5.ListModel> createList(_i5.ListModel? list) =>
      (super.noSuchMethod(
            Invocation.method(#createList, [list]),
            returnValue: _i8.Future<_i5.ListModel>.value(
              _FakeListModel_3(this, Invocation.method(#createList, [list])),
            ),
          )
          as _i8.Future<_i5.ListModel>);

  @override
  _i8.Future<_i5.ListModel> updateList(_i5.ListModel? list) =>
      (super.noSuchMethod(
            Invocation.method(#updateList, [list]),
            returnValue: _i8.Future<_i5.ListModel>.value(
              _FakeListModel_3(this, Invocation.method(#updateList, [list])),
            ),
          )
          as _i8.Future<_i5.ListModel>);

  @override
  _i8.Future<void> deleteList(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteList, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> reorderLists(String? spaceId, List<String>? orderedIds) =>
      (super.noSuchMethod(
            Invocation.method(#reorderLists, [spaceId, orderedIds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i6.ListItem>> getListItemsForList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#getListItemsForList, [listId]),
            returnValue: _i8.Future<List<_i6.ListItem>>.value(<_i6.ListItem>[]),
          )
          as _i8.Future<List<_i6.ListItem>>);

  @override
  _i8.Future<_i6.ListItem> createListItem(_i6.ListItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#createListItem, [item]),
            returnValue: _i8.Future<_i6.ListItem>.value(
              _FakeListItem_4(this, Invocation.method(#createListItem, [item])),
            ),
          )
          as _i8.Future<_i6.ListItem>);

  @override
  _i8.Future<_i6.ListItem> updateListItem(_i6.ListItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateListItem, [item]),
            returnValue: _i8.Future<_i6.ListItem>.value(
              _FakeListItem_4(this, Invocation.method(#updateListItem, [item])),
            ),
          )
          as _i8.Future<_i6.ListItem>);

  @override
  _i8.Future<void> deleteListItem(String? id, String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteListItem, [id, listId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.ListItem> toggleListItem(_i6.ListItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#toggleListItem, [item]),
            returnValue: _i8.Future<_i6.ListItem>.value(
              _FakeListItem_4(this, Invocation.method(#toggleListItem, [item])),
            ),
          )
          as _i8.Future<_i6.ListItem>);

  @override
  _i8.Future<void> reorderListItems(String? listId, List<String>? orderedIds) =>
      (super.noSuchMethod(
            Invocation.method(#reorderListItems, [listId, orderedIds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
