// Mocks generated by Mockito 5.4.6 from annotations
// in later_mobile/test/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i4;

import 'package:flutter/material.dart' as _i14;
import 'package:later_mobile/data/models/list_item_model.dart' as _i12;
import 'package:later_mobile/data/models/list_model.dart' as _i9;
import 'package:later_mobile/data/models/note_model.dart' as _i10;
import 'package:later_mobile/data/models/space_model.dart' as _i6;
import 'package:later_mobile/data/models/todo_item_model.dart' as _i11;
import 'package:later_mobile/data/models/todo_list_model.dart' as _i8;
import 'package:later_mobile/providers/auth_provider.dart' as _i2;
import 'package:later_mobile/providers/content_provider.dart' as _i7;
import 'package:later_mobile/providers/spaces_provider.dart' as _i5;
import 'package:later_mobile/providers/theme_provider.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i2.AuthProvider {
  @override
  _i2.AuthStatus get authStatus =>
      (super.noSuchMethod(
            Invocation.getter(#authStatus),
            returnValue: _i2.AuthStatus.authenticated,
            returnValueForMissingStub: _i2.AuthStatus.authenticated,
          )
          as _i2.AuthStatus);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> signUp({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SpacesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpacesProvider extends _i1.Mock implements _i5.SpacesProvider {
  @override
  List<_i6.Space> get spaces =>
      (super.noSuchMethod(
            Invocation.getter(#spaces),
            returnValue: <_i6.Space>[],
            returnValueForMissingStub: <_i6.Space>[],
          )
          as List<_i6.Space>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> loadSpaces({bool? includeArchived = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loadSpaces, [], {
              #includeArchived: includeArchived,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addSpace(_i6.Space? space) =>
      (super.noSuchMethod(
            Invocation.method(#addSpace, [space]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSpace(_i6.Space? space) =>
      (super.noSuchMethod(
            Invocation.method(#updateSpace, [space]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSpace(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSpace, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> switchSpace(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#switchSpace, [spaceId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getSpaceItemCount(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getSpaceItemCount, [spaceId]),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ContentProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentProvider extends _i1.Mock implements _i7.ContentProvider {
  @override
  List<_i8.TodoList> get todoLists =>
      (super.noSuchMethod(
            Invocation.getter(#todoLists),
            returnValue: <_i8.TodoList>[],
            returnValueForMissingStub: <_i8.TodoList>[],
          )
          as List<_i8.TodoList>);

  @override
  List<_i9.ListModel> get lists =>
      (super.noSuchMethod(
            Invocation.getter(#lists),
            returnValue: <_i9.ListModel>[],
            returnValueForMissingStub: <_i9.ListModel>[],
          )
          as List<_i9.ListModel>);

  @override
  List<_i10.Note> get notes =>
      (super.noSuchMethod(
            Invocation.getter(#notes),
            returnValue: <_i10.Note>[],
            returnValueForMissingStub: <_i10.Note>[],
          )
          as List<_i10.Note>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> loadSpaceContent(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#loadSpaceContent, [spaceId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createTodoList(_i8.TodoList? todoList) =>
      (super.noSuchMethod(
            Invocation.method(#createTodoList, [todoList]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTodoList(_i8.TodoList? todoList) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodoList, [todoList]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTodoList(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodoList, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i11.TodoItem>> loadTodoItemsForList(String? todoListId) =>
      (super.noSuchMethod(
            Invocation.method(#loadTodoItemsForList, [todoListId]),
            returnValue: _i3.Future<List<_i11.TodoItem>>.value(
              <_i11.TodoItem>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i11.TodoItem>>.value(
              <_i11.TodoItem>[],
            ),
          )
          as _i3.Future<List<_i11.TodoItem>>);

  @override
  _i3.Future<void> createTodoItem(_i11.TodoItem? todoItem) =>
      (super.noSuchMethod(
            Invocation.method(#createTodoItem, [todoItem]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTodoItem(_i11.TodoItem? todoItem) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodoItem, [todoItem]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTodoItem(String? todoItemId, String? todoListId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodoItem, [todoItemId, todoListId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reorderTodoItems(
    String? todoListId,
    List<_i11.TodoItem>? items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderTodoItems, [todoListId, items]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createList(_i9.ListModel? list) =>
      (super.noSuchMethod(
            Invocation.method(#createList, [list]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateList(_i9.ListModel? list) =>
      (super.noSuchMethod(
            Invocation.method(#updateList, [list]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteList(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteList, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i12.ListItem>> loadListItemsForList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#loadListItemsForList, [listId]),
            returnValue: _i3.Future<List<_i12.ListItem>>.value(
              <_i12.ListItem>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i12.ListItem>>.value(
              <_i12.ListItem>[],
            ),
          )
          as _i3.Future<List<_i12.ListItem>>);

  @override
  _i3.Future<void> createListItem(_i12.ListItem? listItem) =>
      (super.noSuchMethod(
            Invocation.method(#createListItem, [listItem]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateListItem(_i12.ListItem? listItem) =>
      (super.noSuchMethod(
            Invocation.method(#updateListItem, [listItem]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteListItem(String? listItemId, String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteListItem, [listItemId, listId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reorderListItems(
    String? listId,
    List<_i12.ListItem>? items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderListItems, [listId, items]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reorderContent(
    _i7.ContentFilter? filter,
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderContent, [filter, oldIndex, newIndex]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createNote(_i10.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#createNote, [note]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateNote(_i10.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<dynamic> getFilteredContent(_i7.ContentFilter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#getFilteredContent, [filter]),
            returnValue: <dynamic>[],
            returnValueForMissingStub: <dynamic>[],
          )
          as List<dynamic>);

  @override
  int getTotalCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalCount, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<dynamic> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: <dynamic>[],
            returnValueForMissingStub: <dynamic>[],
          )
          as List<dynamic>);

  @override
  _i3.Future<List<_i8.TodoList>> getTodosWithDueDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getTodosWithDueDate, [date]),
            returnValue: _i3.Future<List<_i8.TodoList>>.value(<_i8.TodoList>[]),
            returnValueForMissingStub: _i3.Future<List<_i8.TodoList>>.value(
              <_i8.TodoList>[],
            ),
          )
          as _i3.Future<List<_i8.TodoList>>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i13.ThemeProvider {
  @override
  _i14.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i14.ThemeMode.system,
            returnValueForMissingStub: _i14.ThemeMode.system,
          )
          as _i14.ThemeMode);

  @override
  bool get isTransitioning =>
      (super.noSuchMethod(
            Invocation.getter(#isTransitioning),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDarkMode =>
      (super.noSuchMethod(
            Invocation.getter(#isDarkMode),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> loadThemePreference() =>
      (super.noSuchMethod(
            Invocation.method(#loadThemePreference, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setThemeMode(_i14.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [mode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleTheme() =>
      (super.noSuchMethod(
            Invocation.method(#toggleTheme, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
