// Mocks generated by Mockito 5.4.6 from annotations
// in later_mobile/test/features/notes/application/services/note_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:later_mobile/features/notes/data/repositories/note_repository.dart'
    as _i5;
import 'package:later_mobile/features/notes/domain/models/note.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNote_1 extends _i1.SmartFake implements _i3.Note {
  _FakeNote_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_2<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteRepository extends _i1.Mock implements _i5.NoteRepository {
  MockNoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get supabase =>
      (super.noSuchMethod(
            Invocation.getter(#supabase),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabase),
            ),
          )
          as _i2.SupabaseClient);

  @override
  String get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
          )
          as String);

  @override
  _i4.Future<_i3.Note> create(_i3.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#create, [note]),
            returnValue: _i4.Future<_i3.Note>.value(
              _FakeNote_1(this, Invocation.method(#create, [note])),
            ),
          )
          as _i4.Future<_i3.Note>);

  @override
  _i4.Future<_i3.Note?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i3.Note?>.value(),
          )
          as _i4.Future<_i3.Note?>);

  @override
  _i4.Future<List<_i3.Note>> getBySpace(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getBySpace, [spaceId]),
            returnValue: _i4.Future<List<_i3.Note>>.value(<_i3.Note>[]),
          )
          as _i4.Future<List<_i3.Note>>);

  @override
  _i4.Future<_i3.Note> update(_i3.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#update, [note]),
            returnValue: _i4.Future<_i3.Note>.value(
              _FakeNote_1(this, Invocation.method(#update, [note])),
            ),
          )
          as _i4.Future<_i3.Note>);

  @override
  _i4.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> deleteAllInSpace(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllInSpace, [spaceId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> countBySpace(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#countBySpace, [spaceId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i3.Note>> getByTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#getByTag, [tag]),
            returnValue: _i4.Future<List<_i3.Note>>.value(<_i3.Note>[]),
          )
          as _i4.Future<List<_i3.Note>>);

  @override
  _i4.Future<List<_i3.Note>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i4.Future<List<_i3.Note>>.value(<_i3.Note>[]),
          )
          as _i4.Future<List<_i3.Note>>);

  @override
  _i4.Future<void> updateSortOrders(List<_i3.Note>? notes) =>
      (super.noSuchMethod(
            Invocation.method(#updateSortOrders, [notes]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<T> executeQuery<T>(_i4.Future<T> Function()? query) =>
      (super.noSuchMethod(
            Invocation.method(#executeQuery, [query]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#executeQuery, [query]),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_2<T>(
                  this,
                  Invocation.method(#executeQuery, [query]),
                ),
          )
          as _i4.Future<T>);
}
