targets:
  $default:
    builders:
      riverpod_generator:
        options:
          # Generate only required files (fewer files for faster builds)
          # Options: all, watch, build
          generate_builder: true
