// Mocks generated by Mockito 5.4.6 from annotations
// in later_mobile/test/features/todo_lists/presentation/controllers/todo_lists_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:later_mobile/features/todo_lists/application/services/todo_list_service.dart'
    as _i4;
import 'package:later_mobile/features/todo_lists/domain/models/todo_item.dart'
    as _i3;
import 'package:later_mobile/features/todo_lists/domain/models/todo_list.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTodoList_0 extends _i1.SmartFake implements _i2.TodoList {
  _FakeTodoList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTodoItem_1 extends _i1.SmartFake implements _i3.TodoItem {
  _FakeTodoItem_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoListService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoListService extends _i1.Mock implements _i4.TodoListService {
  MockTodoListService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.TodoList>> getTodoListsForSpace(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodoListsForSpace, [spaceId]),
            returnValue: _i5.Future<List<_i2.TodoList>>.value(<_i2.TodoList>[]),
          )
          as _i5.Future<List<_i2.TodoList>>);

  @override
  _i5.Future<_i2.TodoList> createTodoList(_i2.TodoList? todoList) =>
      (super.noSuchMethod(
            Invocation.method(#createTodoList, [todoList]),
            returnValue: _i5.Future<_i2.TodoList>.value(
              _FakeTodoList_0(
                this,
                Invocation.method(#createTodoList, [todoList]),
              ),
            ),
          )
          as _i5.Future<_i2.TodoList>);

  @override
  _i5.Future<_i2.TodoList> updateTodoList(_i2.TodoList? todoList) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodoList, [todoList]),
            returnValue: _i5.Future<_i2.TodoList>.value(
              _FakeTodoList_0(
                this,
                Invocation.method(#updateTodoList, [todoList]),
              ),
            ),
          )
          as _i5.Future<_i2.TodoList>);

  @override
  _i5.Future<void> deleteTodoList(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodoList, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> reorderTodoLists(
    String? spaceId,
    List<String>? orderedIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderTodoLists, [spaceId, orderedIds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.TodoItem>> getTodoItemsForList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodoItemsForList, [listId]),
            returnValue: _i5.Future<List<_i3.TodoItem>>.value(<_i3.TodoItem>[]),
          )
          as _i5.Future<List<_i3.TodoItem>>);

  @override
  _i5.Future<_i3.TodoItem> createTodoItem(_i3.TodoItem? todoItem) =>
      (super.noSuchMethod(
            Invocation.method(#createTodoItem, [todoItem]),
            returnValue: _i5.Future<_i3.TodoItem>.value(
              _FakeTodoItem_1(
                this,
                Invocation.method(#createTodoItem, [todoItem]),
              ),
            ),
          )
          as _i5.Future<_i3.TodoItem>);

  @override
  _i5.Future<_i3.TodoItem> updateTodoItem(_i3.TodoItem? todoItem) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodoItem, [todoItem]),
            returnValue: _i5.Future<_i3.TodoItem>.value(
              _FakeTodoItem_1(
                this,
                Invocation.method(#updateTodoItem, [todoItem]),
              ),
            ),
          )
          as _i5.Future<_i3.TodoItem>);

  @override
  _i5.Future<void> deleteTodoItem(String? id, String? todoListId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodoItem, [id, todoListId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.TodoItem> toggleTodoItem(String? id, String? todoListId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTodoItem, [id, todoListId]),
            returnValue: _i5.Future<_i3.TodoItem>.value(
              _FakeTodoItem_1(
                this,
                Invocation.method(#toggleTodoItem, [id, todoListId]),
              ),
            ),
          )
          as _i5.Future<_i3.TodoItem>);

  @override
  _i5.Future<void> reorderTodoItems(String? listId, List<String>? orderedIds) =>
      (super.noSuchMethod(
            Invocation.method(#reorderTodoItems, [listId, orderedIds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
