// Mocks generated by Mockito 5.4.6 from annotations
// in later_mobile/test/features/todo_lists/application/services/todo_list_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:later_mobile/features/todo_lists/data/repositories/todo_list_repository.dart'
    as _i6;
import 'package:later_mobile/features/todo_lists/domain/models/todo_item.dart'
    as _i4;
import 'package:later_mobile/features/todo_lists/domain/models/todo_list.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTodoList_1 extends _i1.SmartFake implements _i3.TodoList {
  _FakeTodoList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTodoItem_2 extends _i1.SmartFake implements _i4.TodoItem {
  _FakeTodoItem_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_3<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoListRepository extends _i1.Mock
    implements _i6.TodoListRepository {
  MockTodoListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get supabase =>
      (super.noSuchMethod(
            Invocation.getter(#supabase),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabase),
            ),
          )
          as _i2.SupabaseClient);

  @override
  String get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
          )
          as String);

  @override
  _i5.Future<_i3.TodoList> create(_i3.TodoList? todoList) =>
      (super.noSuchMethod(
            Invocation.method(#create, [todoList]),
            returnValue: _i5.Future<_i3.TodoList>.value(
              _FakeTodoList_1(this, Invocation.method(#create, [todoList])),
            ),
          )
          as _i5.Future<_i3.TodoList>);

  @override
  _i5.Future<_i3.TodoList?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i5.Future<_i3.TodoList?>.value(),
          )
          as _i5.Future<_i3.TodoList?>);

  @override
  _i5.Future<List<_i3.TodoList>> getBySpace(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getBySpace, [spaceId]),
            returnValue: _i5.Future<List<_i3.TodoList>>.value(<_i3.TodoList>[]),
          )
          as _i5.Future<List<_i3.TodoList>>);

  @override
  _i5.Future<_i3.TodoList> update(_i3.TodoList? todoList) =>
      (super.noSuchMethod(
            Invocation.method(#update, [todoList]),
            returnValue: _i5.Future<_i3.TodoList>.value(
              _FakeTodoList_1(this, Invocation.method(#update, [todoList])),
            ),
          )
          as _i5.Future<_i3.TodoList>);

  @override
  _i5.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i4.TodoItem>> getTodoItemsByListId(String? todoListId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodoItemsByListId, [todoListId]),
            returnValue: _i5.Future<List<_i4.TodoItem>>.value(<_i4.TodoItem>[]),
          )
          as _i5.Future<List<_i4.TodoItem>>);

  @override
  _i5.Future<_i4.TodoItem> createTodoItem(_i4.TodoItem? todoItem) =>
      (super.noSuchMethod(
            Invocation.method(#createTodoItem, [todoItem]),
            returnValue: _i5.Future<_i4.TodoItem>.value(
              _FakeTodoItem_2(
                this,
                Invocation.method(#createTodoItem, [todoItem]),
              ),
            ),
          )
          as _i5.Future<_i4.TodoItem>);

  @override
  _i5.Future<_i4.TodoItem> updateTodoItem(_i4.TodoItem? todoItem) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodoItem, [todoItem]),
            returnValue: _i5.Future<_i4.TodoItem>.value(
              _FakeTodoItem_2(
                this,
                Invocation.method(#updateTodoItem, [todoItem]),
              ),
            ),
          )
          as _i5.Future<_i4.TodoItem>);

  @override
  _i5.Future<void> deleteTodoItem(String? id, String? todoListId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodoItem, [id, todoListId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateTodoItemSortOrders(List<_i4.TodoItem>? todoItems) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodoItemSortOrders, [todoItems]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> executeQuery<T>(_i5.Future<T> Function()? query) =>
      (super.noSuchMethod(
            Invocation.method(#executeQuery, [query]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#executeQuery, [query]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_3<T>(
                  this,
                  Invocation.method(#executeQuery, [query]),
                ),
          )
          as _i5.Future<T>);
}
