// Mocks generated by Mockito 5.4.6 from annotations
// in later_mobile/test/features/search/application/services/search_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:later_mobile/features/search/data/repositories/search_repository.dart'
    as _i4;
import 'package:later_mobile/features/search/domain/models/search_query.dart'
    as _i7;
import 'package:later_mobile/features/search/domain/models/search_result.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i4.SearchRepository {
  @override
  _i2.SupabaseClient get supabase =>
      (super.noSuchMethod(
            Invocation.getter(#supabase),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabase),
            ),
            returnValueForMissingStub: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabase),
            ),
          )
          as _i2.SupabaseClient);

  @override
  String get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
          )
          as String);

  @override
  _i3.Future<List<_i6.SearchResult>> search(_i7.SearchQuery? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i3.Future<List<_i6.SearchResult>>.value(
              <_i6.SearchResult>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i6.SearchResult>>.value(
              <_i6.SearchResult>[],
            ),
          )
          as _i3.Future<List<_i6.SearchResult>>);

  @override
  _i3.Future<T> executeQuery<T>(_i3.Future<T> Function()? query) =>
      (super.noSuchMethod(
            Invocation.method(#executeQuery, [query]),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#executeQuery, [query]),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(#executeQuery, [query]),
                ),
            returnValueForMissingStub:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#executeQuery, [query]),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(#executeQuery, [query]),
                ),
          )
          as _i3.Future<T>);
}
