// Mocks generated by Mockito 5.4.6 from annotations
// in later_mobile/test/features/spaces/presentation/controllers/spaces_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:later_mobile/features/spaces/application/services/space_service.dart'
    as _i3;
import 'package:later_mobile/features/spaces/domain/models/space.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSpace_0 extends _i1.SmartFake implements _i2.Space {
  _FakeSpace_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SpaceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpaceService extends _i1.Mock implements _i3.SpaceService {
  MockSpaceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Space>> loadSpaces({bool? includeArchived = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loadSpaces, [], {
              #includeArchived: includeArchived,
            }),
            returnValue: _i4.Future<List<_i2.Space>>.value(<_i2.Space>[]),
          )
          as _i4.Future<List<_i2.Space>>);

  @override
  _i4.Future<_i2.Space> createSpace(_i2.Space? space) =>
      (super.noSuchMethod(
            Invocation.method(#createSpace, [space]),
            returnValue: _i4.Future<_i2.Space>.value(
              _FakeSpace_0(this, Invocation.method(#createSpace, [space])),
            ),
          )
          as _i4.Future<_i2.Space>);

  @override
  _i4.Future<_i2.Space> updateSpace(_i2.Space? space) =>
      (super.noSuchMethod(
            Invocation.method(#updateSpace, [space]),
            returnValue: _i4.Future<_i2.Space>.value(
              _FakeSpace_0(this, Invocation.method(#updateSpace, [space])),
            ),
          )
          as _i4.Future<_i2.Space>);

  @override
  _i4.Future<void> deleteSpace(String? spaceId, String? currentSpaceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSpace, [spaceId, currentSpaceId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Space> archiveSpace(_i2.Space? space) =>
      (super.noSuchMethod(
            Invocation.method(#archiveSpace, [space]),
            returnValue: _i4.Future<_i2.Space>.value(
              _FakeSpace_0(this, Invocation.method(#archiveSpace, [space])),
            ),
          )
          as _i4.Future<_i2.Space>);

  @override
  _i4.Future<_i2.Space> unarchiveSpace(_i2.Space? space) =>
      (super.noSuchMethod(
            Invocation.method(#unarchiveSpace, [space]),
            returnValue: _i4.Future<_i2.Space>.value(
              _FakeSpace_0(this, Invocation.method(#unarchiveSpace, [space])),
            ),
          )
          as _i4.Future<_i2.Space>);

  @override
  _i4.Future<int> getSpaceItemCount(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getSpaceItemCount, [spaceId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
