// Mocks generated by Mockito 5.4.6 from annotations
// in later_mobile/test/features/theme/presentation/controllers/theme_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i3;
import 'package:later_mobile/features/theme/application/theme_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ThemeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeService extends _i1.Mock implements _i2.ThemeService {
  MockThemeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ThemeMode loadThemePreference() =>
      (super.noSuchMethod(
            Invocation.method(#loadThemePreference, []),
            returnValue: _i3.ThemeMode.system,
          )
          as _i3.ThemeMode);

  @override
  _i4.Future<void> saveThemePreference(_i3.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#saveThemePreference, [mode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i3.ThemeMode parseThemeMode(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#parseThemeMode, [value]),
            returnValue: _i3.ThemeMode.system,
          )
          as _i3.ThemeMode);

  @override
  bool isDarkMode(_i3.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#isDarkMode, [mode]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.ThemeMode getNextThemeMode(_i3.ThemeMode? currentMode) =>
      (super.noSuchMethod(
            Invocation.method(#getNextThemeMode, [currentMode]),
            returnValue: _i3.ThemeMode.system,
          )
          as _i3.ThemeMode);
}
