// Mocks generated by Mockito 5.4.6 from annotations
// in later_mobile/test/features/lists/application/services/list_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:later_mobile/features/lists/data/repositories/list_repository.dart'
    as _i6;
import 'package:later_mobile/features/lists/domain/models/list_item_model.dart'
    as _i4;
import 'package:later_mobile/features/lists/domain/models/list_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListModel_1 extends _i1.SmartFake implements _i3.ListModel {
  _FakeListModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListItem_2 extends _i1.SmartFake implements _i4.ListItem {
  _FakeListItem_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_3<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockListRepository extends _i1.Mock implements _i6.ListRepository {
  MockListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get supabase =>
      (super.noSuchMethod(
            Invocation.getter(#supabase),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabase),
            ),
          )
          as _i2.SupabaseClient);

  @override
  String get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
          )
          as String);

  @override
  _i5.Future<_i3.ListModel> create(_i3.ListModel? list) =>
      (super.noSuchMethod(
            Invocation.method(#create, [list]),
            returnValue: _i5.Future<_i3.ListModel>.value(
              _FakeListModel_1(this, Invocation.method(#create, [list])),
            ),
          )
          as _i5.Future<_i3.ListModel>);

  @override
  _i5.Future<_i3.ListModel?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i5.Future<_i3.ListModel?>.value(),
          )
          as _i5.Future<_i3.ListModel?>);

  @override
  _i5.Future<List<_i3.ListModel>> getBySpace(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getBySpace, [spaceId]),
            returnValue: _i5.Future<List<_i3.ListModel>>.value(
              <_i3.ListModel>[],
            ),
          )
          as _i5.Future<List<_i3.ListModel>>);

  @override
  _i5.Future<_i3.ListModel> update(_i3.ListModel? list) =>
      (super.noSuchMethod(
            Invocation.method(#update, [list]),
            returnValue: _i5.Future<_i3.ListModel>.value(
              _FakeListModel_1(this, Invocation.method(#update, [list])),
            ),
          )
          as _i5.Future<_i3.ListModel>);

  @override
  _i5.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i4.ListItem>> getListItemsByListId(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#getListItemsByListId, [listId]),
            returnValue: _i5.Future<List<_i4.ListItem>>.value(<_i4.ListItem>[]),
          )
          as _i5.Future<List<_i4.ListItem>>);

  @override
  _i5.Future<_i4.ListItem> createListItem(_i4.ListItem? listItem) =>
      (super.noSuchMethod(
            Invocation.method(#createListItem, [listItem]),
            returnValue: _i5.Future<_i4.ListItem>.value(
              _FakeListItem_2(
                this,
                Invocation.method(#createListItem, [listItem]),
              ),
            ),
          )
          as _i5.Future<_i4.ListItem>);

  @override
  _i5.Future<_i4.ListItem> updateListItem(_i4.ListItem? listItem) =>
      (super.noSuchMethod(
            Invocation.method(#updateListItem, [listItem]),
            returnValue: _i5.Future<_i4.ListItem>.value(
              _FakeListItem_2(
                this,
                Invocation.method(#updateListItem, [listItem]),
              ),
            ),
          )
          as _i5.Future<_i4.ListItem>);

  @override
  _i5.Future<void> deleteListItem(String? id, String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteListItem, [id, listId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateListItemSortOrders(List<_i4.ListItem>? listItems) =>
      (super.noSuchMethod(
            Invocation.method(#updateListItemSortOrders, [listItems]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> executeQuery<T>(_i5.Future<T> Function()? query) =>
      (super.noSuchMethod(
            Invocation.method(#executeQuery, [query]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#executeQuery, [query]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_3<T>(
                  this,
                  Invocation.method(#executeQuery, [query]),
                ),
          )
          as _i5.Future<T>);
}
