// Mocks generated by Mockito 5.4.6 from annotations
// in later_mobile/test/features/theme/application/theme_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:later_mobile/data/local/preferences_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i2.PreferencesService {
  MockPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i3.Future<void> setLastSelectedSpaceId(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#setLastSelectedSpaceId, [spaceId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearLastSelectedSpaceId() =>
      (super.noSuchMethod(
            Invocation.method(#clearLastSelectedSpaceId, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setThemeMode(String? themeMode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [themeMode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool hasMigratedToCalculatedCounts() =>
      (super.noSuchMethod(
            Invocation.method(#hasMigratedToCalculatedCounts, []),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> setMigratedToCalculatedCounts() =>
      (super.noSuchMethod(
            Invocation.method(#setMigratedToCalculatedCounts, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool hasMigratedSortOrder() =>
      (super.noSuchMethod(
            Invocation.method(#hasMigratedSortOrder, []),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> setMigratedSortOrder() =>
      (super.noSuchMethod(
            Invocation.method(#setMigratedSortOrder, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  Map<String, dynamic> getAllPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPreferences, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );
}
